# Generated by Django 4.0.1 on 2022-01-09 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0002_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
    ]
